FROM node:16 as builder

WORKDIR /usr/src/app/api/

COPY package.json /usr/src/app/api/
COPY yarn.lock /usr/src/app/api/
COPY prisma ./prisma/

RUN yarn install
RUN npx prisma generate

COPY . .

RUN yarn build

FROM node:16

WORKDIR /usr/src/app/api/

COPY --from=builder /usr/src/app/api/prisma ./prisma
COPY --from=builder /usr/src/app/api/node_modules ./node_modules
COPY --from=builder /usr/src/app/api/package*.json ./
COPY --from=builder /usr/src/app/api/dist ./dist
COPY --from=builder /usr/src/app/api/yarn.lock ./

EXPOSE 4000

CMD ["yarn", "start:prod", "-i max"]