FROM node:16 as builder

WORKDIR /usr/src/app/client/

COPY package.json /usr/src/app/client/
COPY yarn.lock /usr/src/app/client/

RUN yarn install --legacy-peer-deps
RUN yarn add serve

COPY . .

RUN yarn build

FROM node:16

WORKDIR /usr/src/app/client/

COPY --from=builder /usr/src/app/client/node_modules ./node_modules
COPY --from=builder /usr/src/app/client/package*.json ./
COPY --from=builder /usr/src/app/client/yarn.lock ./

EXPOSE 3000

CMD ["yarn", "prod"]